# Generated by Django 4.2.2 on 2023-06-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='weekly_attendees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
