# Generated by Django 4.2.2 on 2023-06-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_formdata_weekly_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='street_address',
            field=models.CharField(max_length=200),
        ),
    ]
