# Generated by Django 4.2.2 on 2023-06-29 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_formdata_street_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormData',
        ),
    ]
