# Generated by Django 4.2.2 on 2023-07-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('organization_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('instagram_followers', models.IntegerField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True)),
                ('facebook_followers', models.IntegerField(blank=True, null=True)),
                ('ticktock', models.URLField(blank=True)),
                ('ticktock_followers', models.IntegerField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True)),
                ('twitter_followers', models.IntegerField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True)),
                ('youtube_followers', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('notes', models.TextField()),
                ('is_church', models.BooleanField(default=False)),
                ('is_organization', models.BooleanField(default=False)),
                ('is_influencer', models.BooleanField(default=False)),
                ('is_media', models.BooleanField(default=False)),
                ('services', models.CharField(max_length=100)),
                ('weekly_attendees', models.IntegerField(blank=True, null=True)),
                ('has_supported', models.CharField(max_length=100)),
            ],
        ),
    ]
