# Generated by Django 4.2.2 on 2023-07-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
